%% making a list of all days in the dataset
TT2 = timetable(featuresData.hour,featuresData.heart);
Days = retime(TT2,'daily');
%% making a variable of all days on form dd-MM-uuuu
All_dates = datetime(Days.Time,'Format','dd-MMM-uuuu');
All_dates = All_dates';
%% selecting one day randomly from x numbers of 7 days perioeds
k=1;
for i=1:round(length(All_dates)/7)
    if (((length(All_dates)-k)< 7))
        dates_to_validations_set(i,:) = All_dates(1,(randi([k length(All_dates)],1)));
    end
    if (k==1)
        dates_to_validations_set(i,:) = All_dates(1,(randi([k (k+6)],1)));
        k=8; 
    end
    if (((length(All_dates)-k)>6) && i>1)
       dates_to_validations_set(i,:) = All_dates(1,(randi([k (k+6)],1)));
       k=k+7; 
    end
end
%% extrating data from featuresData to validation set based on days randomly picked in dates_to_validations_set
k=1;
for i=0:(length(dates_to_validations_set))
    for j=1:length(featuresData.hour)
        if (day(dates_to_validations_set(i+1,1),'dayofyear') == day(featuresData.hour(j),'dayofyear'))
            validation_set(k,:) = table(featuresData.hour(j),featuresData.heart(j),featuresData.heart_diff(j),...
                featuresData.heart_diff_movmax(j),featuresData.heart_diff_movmean(j),featuresData.heart_diff_movmin(j),...
                featuresData.heart_diff_movmin(j),featuresData.heart_movmedian_1h(j),featuresData.heart_movmin_1h(j),...
                featuresData.heart_movmax_1h(j),featuresData.heart_movstd_1h(j),featuresData.delay_heart_5m(j),...
                featuresData.delay_heart_15m(j),featuresData.delay_heart_1h(j),featuresData.delay_heart_5h(j),...
                featuresData.steps(j),featuresData.steps_diff(j),featuresData.steps_movmean(j),featuresData.steps_movmedian(j),...
                featuresData.steps_movmin(j),featuresData.steps_movmax(j),featuresData.steps_movstd(j),...
                featuresData.delay_steps_5m(j),featuresData.delay_steps_15m(j),featuresData.delay_steps_1h(j),...
                featuresData.delay_steps_5h(j),featuresData.sleeptime(j),featuresData.sleepaverage(j),...
                featuresData.delay_heart_diff_5m(j),featuresData.delay_heart_diff_15m(j),featuresData.delay_heart_diff_1h(j),...
                featuresData.delay_heart_diff_5h(j),featuresData.delay_steps_diff_5m(j),featuresData.delay_steps_diff_15m(j),...
                featuresData.delay_steps_diff_1h(j),featuresData.delay_steps_diff_5h(j),featuresData.heart_movmedian_15m(j),...
                featuresData.heart_movmean_15m(j),featuresData.heart_movmin_15m(j),featuresData.heart_movmax_15m(j),...
                featuresData.heart_movstd_15m(j),featuresData.steps_movmean_15m(j),featuresData.steps_movmedian_15m(j),...
                featuresData.steps_movmin_15m(j),featuresData.steps_movmax_15m(j),featuresData.steps_movstd_15m(j),...
                featuresData.heart_movstd_1m_delay_5m(j),featuresData.heart_movstd_5m_delay_15m(j),...
                featuresData.heart_movstd_15m_delay_1h(j),featuresData.heart_movstd_2h_delay_5h(j),...
                featuresData.heart_movmean_1m_delay_5m(j),featuresData.heart_movmean_5m_delay_15m(j),...
                featuresData.heart_movmean_2h_delay_5h(j),featuresData.step_movstd_1m_delay_5m(j),...
                featuresData.step_movstd_5m_delay_15m(j),featuresData.step_movstd_15m_delay_1h(j),...
                featuresData.step_movstd_2h_delay_5h(j),featuresData.step_movmean_1m_delay_5m(j),...
                featuresData.step_movmean_5m_delay_15m(j),featuresData.step_movmean_15m_delay_1h(j),...
                featuresData.step_movmean_2h_delay_5h(j),featuresData.fluidmodel(j),featuresData.headache(j));
            k=k+1;
            row_number(k,1) = j;
        end
    end
        
end
%% Delete valdiation data from featuresData
row_number = flip(row_number);
for i=1:length(row_number)
    featuresData(row_number(i),:) = [];
end


%% Splitting featuresData into training and test 
[m,n] = size(featuresData) ;
P = 0.70 ; % train = 70% of data and test = 30%
idx = randperm(m)  ; % scrambling the data
Training = featuresData(idx(1:round(P*m)),:) ;
Testing = featuresData(idx(round(P*m)+1:end),:) ;
    


