function stepsJacob = importSteps(workbookFile, sheetName, startRow, endRow)
%IMPORTFILE1 Import data from a spreadsheet
%  JACOBSTEPS = IMPORTFILE1(FILE) reads data from the first worksheet in
%  the Microsoft Excel spreadsheet file named FILE.  Returns the data as
%  a table.
%
%  JACOBSTEPS = IMPORTFILE1(FILE, SHEET) reads from the specified
%  worksheet.
%
%  JACOBSTEPS = IMPORTFILE1(FILE, SHEET, STARTROW, ENDROW) reads from
%  the specified worksheet for the specified row interval(s). Specify
%  STARTROW and ENDROW as a pair of scalars or vectors of matching size
%  for dis-contiguous row intervals.
%
%  Example:
%  JacobSteps = importfile1("C:\Users\anneh\Documents\st7-18gr7403\patterne-recognition-tests\Jacob_Steps.xlsx", "Ark1", 2, 17281);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 09-Oct-2018 09:29:37

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 3
    startRow = 2;
    endRow = 17281;
end

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 2);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + startRow(1) + ":B" + endRow(1);

% Specify column names and types
opts.VariableNames = ["Date", "steps"];
opts.VariableTypes = ["string", "double"];
opts = setvaropts(opts, 1, "WhitespaceRule", "preserve");
opts = setvaropts(opts, 1, "EmptyFieldRule", "auto");

% Import the data
stepsJacob = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:length(startRow)
    opts.DataRange = "A" + startRow(idx) + ":B" + endRow(idx);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    stepsJacob = [stepsJacob; tb]; %#ok<AGROW>
end

end