function fitbitsleepjacob = importSleepData(workbookFile, sheetName, startRow, endRow)
%IMPORTFILE1 Import data from a spreadsheet
%  FITBITSLEEPJACOB = IMPORTFILE1(FILE) reads data from the first
%  worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the data as a table.
%
%  FITBITSLEEPJACOB = IMPORTFILE1(FILE, SHEET) reads from the specified
%  worksheet.
%
%  FITBITSLEEPJACOB = IMPORTFILE1(FILE, SHEET, STARTROW, ENDROW) reads
%  from the specified worksheet for the specified row interval(s).
%  Specify STARTROW and ENDROW as a pair of scalars or vectors of
%  matching size for dis-contiguous row intervals.
%
%  Example:
%  fitbitsleepjacob = importfile1("C:\Users\Admin\Documents\Git\st7-18gr7403\patterne-recognition-tests\fitbit_sleep_jacob.xls", "Sleep", 1, 15);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 04-Oct-2018 12:51:45

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 3
    startRow = 1;
    endRow = 15;
end

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 9);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + startRow(1) + ":I" + endRow(1);

% Specify column names and types
opts.VariableNames = ["StartTime", "EndTime", "MinutesAsleep", "MinutesAwake", "NumberofAwakenings", "TimeinBed", "MinutesREMSleep", "MinutesLightSleep", "MinutesDeepSleep"];
opts.VariableTypes = ["string", "string", "string", "string", "string", "string", "string", "string", "string"];
opts = setvaropts(opts, [1, 2, 3, 4, 5, 6, 7, 8, 9], "WhitespaceRule", "preserve");
opts = setvaropts(opts, [1, 2, 3, 4, 5, 6, 7, 8, 9], "EmptyFieldRule", "auto");

% Import the data
fitbitsleepjacob = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:length(startRow)
    opts.DataRange = "A" + startRow(idx) + ":I" + endRow(idx);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    fitbitsleepjacob = [fitbitsleepjacob; tb]; %#ok<AGROW>
end

end